version: 0.0
os: linux
files:
   - source: .
     destination: /var/www/proak-dota2
hooks:
   BeforeInstall:
     - location: scripts/beforeinstall.sh
       timout: 300
       runas: root
   AfterInstall:
     - location: scripts/afterinstall.sh
       timeout: 300
       runas: root
